### ISSUE TITLE
2.4.2: Class Faonni\ProductAvailable\Model\Config\Source\Customer\Group not found in AbstractFactory.php

### ISSUE THREAD

**Issue by klou** [karliuka/m2.ProductAvailable#19]
```
[2023-06-07T22:56:23.013683+00:00] main.CRITICAL: Error: Class "Faonni\ProductAvailable\Model\Config\Source\Customer\Group" not found in /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
Stack trace:
#0 /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#1 /bitnami/magento/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create()
#2 /bitnami/magento/vendor/magento/module-config/Model/Config/SourceFactory.php(37): Magento\Framework\ObjectManager\ObjectManager->get()
#3 /bitnami/magento/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(443): Magento\Config\Model\Config\SourceFactory->create()
#4 /bitnami/magento/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(379): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel()
#5 /bitnami/magento/generated/code/Magento/Config/Model/Config/Structure/Element/Field/Interceptor.php(230): Magento\Config\Model\Config\Structure\Element\Field->getOptions()
#6 /bitnami/magento/vendor/magento/module-config/Block/System/Config/Form.php(394): Magento\Config\Model\Config\Structure\Element\Field\Interceptor->getOptions()
#7 /bitnami/magento/vendor/magento/module-config/Block/System/Config/Form.php(316): Magento\Config\Block\System\Config\Form->_initElement()
#8 /bitnami/magento/vendor/magento/module-config/Block/System/Config/Form.php(256): Magento\Config\Block\System\Config\Form->initFields()
#9 /bitnami/magento/vendor/magento/module-config/Block/System/Config/Form.php(202): Magento\Config\Block\System\Config\Form->_initGroup()
#10 /bitnami/magento/vendor/magento/module-config/Block/System/Config/Form.php(542): Magento\Config\Block\System\Config\Form->initForm()
#11 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1094): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#12 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#13 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#14 /bitnami/magento/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#15 /bitnami/magento/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#16 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#17 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#18 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#19 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(507): Magento\Framework\View\Layout\Interceptor->renderElement()
#20 /bitnami/magento/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(32): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#21 /bitnami/magento/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#22 /bitnami/magento/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php->render()
#23 /bitnami/magento/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView()
#24 /bitnami/magento/vendor/magento/module-backend/Block/Template.php(141): Magento\Framework\View\Element\Template->_toHtml()
#25 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Backend\Block\Template->_toHtml()
#26 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#27 /bitnami/magento/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#28 /bitnami/magento/vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#29 /bitnami/magento/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock()
#30 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#31 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#32 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#33 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#34 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#35 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#36 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#37 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#38 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#39 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#40 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#41 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#42 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#43 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#44 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#45 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#46 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#47 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#48 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#49 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#50 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#51 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#52 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#53 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#54 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#55 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#56 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#57 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#58 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#59 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#60 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#61 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#62 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#63 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#64 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#65 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#66 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#67 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#68 /bitnami/magento/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement()
#69 /bitnami/magento/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer()
#70 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement()
#71 /bitnami/magento/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#72 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement()
#73 /bitnami/magento/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement()
#74 /bitnami/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout->getOutput()
#75 /bitnami/magento/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#76 /bitnami/magento/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#77 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult()
#78 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Backend\Model\View\Result\Page\Interceptor->___callParent()
#79 /bitnami/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Backend\Model\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}()
#80 /bitnami/magento/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(140): Magento\Backend\Model\View\Result\Page\Interceptor->___callPlugins()
#81 /bitnami/magento/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#82 /bitnami/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#83 /bitnami/magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#84 /bitnami/magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#85 {main} {"exception":"[object] (Error(code: 0): Class \"Faonni\\ProductAvailable\\Model\\Config\\Source\\Customer\\Group\" not found at /bitnami/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121)"} []

```

Is this missing ```di.xml```?  Also, ```~/generated/code/Faonni/ProductAvailable``` does not exist.

**Comment by karliuka** [comment]
looks like an autoload problem

run the install command:
composer require faonni/module-product-available:2.4.*

check if the module exists in the vendor folder:
vendor/faonni/module-product-available

enter following commands:
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy  (optional)

**Comment by klou** [comment]
Thanks for your help.  I've done the install procedures multiple times, and it exists within the ```vendor``` folder.

vendor/composer/autoload-psr4.php
```
...
    'Faonni\\SmartCategory\\' => array($vendorDir . '/faonni/module-smart-category'),
    'Faonni\\SmartCategoryKit\\' => array($vendorDir . '/faonni/module-smart-category-kit'),
    'Faonni\\SmartCategoryConfigurable\\' => array($vendorDir . '/faonni/module-smart-category-configurable'),
    'Faonni\\ProductAvailable\\' => array($vendorDir . '/faonni/module-product-available'),
...
```

vendor/composer/installed.json
```
...
        {
            "name": "faonni/module-product-available",
            "version": "2.4.2",
            "version_normalized": "2.4.2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/karliuka/m2.ProductAvailable.git",
                "reference": "c8e6e793dbe31f073bae9d79ada02f2a350039ed"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/karliuka/m2.ProductAvailable/zipball/c8e6e793dbe31f073bae9d79ada02f2a350039ed",
                "reference": "c8e6e793dbe31f073bae9d79ada02f2a350039ed",
                "shasum": ""
            },
            "require": {
                "magento/framework": "103.0.*",
                "magento/module-config": "101.2.*",
                "magento/module-customer": "103.0.*",
                "magento/module-sales": "103.0.*"
            },
            "time": "2023-06-07T18:50:53+00:00",
            "type": "magento2-module",
            "installation-source": "dist",
            "autoload": {
                "files": [
                    "registration.php"
                ],
                "psr-4": {
                    "Faonni\\ProductAvailable\\": ""
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "OSL-3.0"
            ],
            "authors": [
                {
                    "name": "Karliuka Vitalii",
                    "email": "karliuka.vitalii@gmail.com"
                }
            ],
            "description": "Extension allows the store owner to hide the product price and add to cart button from guests or certain customer groups.",
            "support": {
                "issues": "https://github.com/karliuka/m2.ProductAvailable/issues",
                "source": "https://github.com/karliuka/m2.ProductAvailable/tree/2.4.2"
            },
            "install-path": "../faonni/module-product-available"
        },
...
```

**Comment by klou** [comment]
The above error is when attempting to access Configuration -> Catalog

**Comment by klou** [comment]
I just don't get it.  I get the problems and the above exception error after doing a full extension install.

It looks like it's installed correctly:

```
daemon@2cd3054e62cf:/bitnami/magento$ magento dev:di:info "Faonni\ProductAvailable\Model\Config\Source\Customer\Group"

DI configuration for the class Faonni\ProductAvailable\Model\Config\Source\Customer\Group in the GLOBAL area

Preference: Faonni\ProductAvailable\Model\Config\Source\Customer\Group

Constructor Parameters:
+-------------------+--------------------------------------------------------------+---------------------------------------------------------------------------------------+
| Name              | Requested Type                                               | Configured Value                                                                      |
+-------------------+--------------------------------------------------------------+---------------------------------------------------------------------------------------+
| collectionFactory | Magento\Customer\Model\ResourceModel\Group\CollectionFactory | {                                                                                     |
|                   |                                                              |     "_i_": "string Magento\\Customer\\Model\\ResourceModel\\Group\\CollectionFactory" |
|                   |                                                              | }                                                                                     |
+-------------------+--------------------------------------------------------------+---------------------------------------------------------------------------------------+


Plugins:
+--------+--------+------+
| Plugin | Method | Type |
+--------+--------+------+


Plugins for the Preference:
+--------+--------+------+
| Plugin | Method | Type |
+--------+--------+------+

```

However, after ```magento cache:flush```, I am then able to access the **Configuration -> Catalog** without logging any errors (backend or frontend), but **Product Available*** does not exist here.

**Comment by karliuka** [comment]
I can't reproduce this bug on my instance. What version of php do you have and is there a bug in customer grid (options contain this collection factory)?

**Comment by klou** [comment]
This is PHP 8.1.19 (bitnami docker instance, M2.4.6).

***Config -> Customers -> All Customers*** does not show any errors or reference to "Product Available."

I do have the following modules disabled, though.  Hopefully it doesn't affect things.
```
List of disabled modules:
Magento_Amqp
Magento_WebapiAsync
```

**Comment by klou** [comment]
Unfortunately, the same result for 2.4.6-p1 (CE).  It is really odd that it only throws the error, if I don't flush the cache.  Once the cache is flushed, I can then access the ***Catalog*** config page, though without Product Available.

Do you have any other ideas how I can troubleshoot this?  It seems to me that it's not being deployed properly, for some reason.

**Comment by karliuka** [comment]
Perhaps the problem is due to file permissions. You can show the output of the **ls -l** command of the magento installation directory?

**Comment by klou** [comment]
```
daemon@2cd3054e62cf:/bitnami/magento$ ls -l
total 2300
-rw-r--r--  1 daemon daemon  766543 Jun 13 21:15 CHANGELOG.md
-rw-r--r--  1 daemon daemon     650 Jun 13 21:15 COPYING.txt
drwxr-xr-x 12 daemon daemon    4096 Sep 14  2021 Core-old
-rw-r--r--  1 daemon daemon    2972 Jun 13 21:15 Gruntfile.js.sample
-rw-r--r--  1 daemon daemon   10364 Jun 13 21:15 LICENSE.txt
-rw-r--r--  1 daemon daemon   10376 Jun 13 21:15 LICENSE_AFL.txt
-rw-r--r--  1 daemon daemon     698 Jun 13 21:15 SECURITY.md
drwxrwxr-x  5 daemon daemon    4096 Jun 13 21:15 app
-rw-r--r--  1 daemon root       189 Aug 31  2022 auth.json
-rw-r--r--  1 daemon daemon     150 Jun 13 21:15 auth.json.sample
drwxrwxr-x  2 daemon daemon    4096 Jun 13 21:15 bin
-rw-rw-r--  1 daemon daemon    3480 Jun 13 21:13 composer.json
-rw-r--r--  1 daemon daemon    3477 Jun 13 21:12 composer.json.bak
-rw-r--r--  1 daemon daemon 1021039 Jun 13 21:15 composer.lock
drwxrwxr-x  4 daemon daemon    4096 Jun 13 21:15 dev
-rw-rw-r--  1 daemon daemon     813 Jun 12 19:11 framework-dependencies.csv
drwxrwxr-x  4 daemon daemon    4096 Jun 13 21:19 generated
-rw-r--r--  1 daemon daemon      55 Jun 13 21:15 grunt-config.json.sample
drwxrwxr-x  4 daemon daemon    4096 Jun 13 21:15 lib
drwxrwxr-x  2 daemon daemon    4096 Aug  3  2021 licenses
-rw-rw-r--  1 daemon daemon  345274 Jun 12 19:10 modules-circular-dependencies.csv
-rw-rw-r--  1 daemon daemon   81097 Jun 12 19:10 modules-dependencies.csv
-rw-r--r--  1 daemon daemon    6948 Jun 13 21:15 nginx.conf.sample
-rw-r--r--  1 daemon daemon    1234 Jun 13 21:15 package.json.sample
drwxr-xr-x  2 daemon daemon    4096 Jun 13 21:15 phpserver
drwxrwxr-x  6 daemon daemon    4096 Jun 13 21:15 pub
drwxrwxr-x  7 daemon daemon    4096 Jun 13 21:15 setup
drwxrwxr-x  2 daemon daemon    4096 Aug  3  2021 tmp
drwxrwxr-x  2 daemon daemon    4096 Aug  3  2021 uploads
drwxrwsr-x  7 daemon daemon    4096 Jun 13 21:28 var
drwxrwsr-x 79 daemon daemon    4096 Jun 13 21:15 vendor
```
```
daemon@2cd3054e62cf:/bitnami/magento/vendor/faonni/module-product-available$ ls -l
total 52
-rw-r--r-- 1 daemon daemon   222 Jun  7 11:50 COPYING.txt
drwxr-sr-x 2 daemon daemon  4096 Jun 12 23:31 Helper
-rw-r--r-- 1 daemon daemon 10364 Jun  7 11:50 LICENSE.txt
drwxr-sr-x 3 daemon daemon  4096 Jun 12 23:31 Model
drwxr-sr-x 2 daemon daemon  4096 Jun 12 23:31 Observer
-rw-r--r-- 1 daemon daemon  2712 Jun  7 11:50 README.md
drwxr-sr-x 2 daemon daemon  4096 Jun 12 23:31 Setup
-rw-r--r-- 1 daemon daemon   781 Jun  7 11:50 composer.json
drwxr-sr-x 5 daemon daemon  4096 Jun 12 23:31 etc
drwxr-sr-x 2 daemon daemon  4096 Jun 12 23:31 i18n
-rw-r--r-- 1 daemon daemon   277 Jun  7 11:50 registration.php
```
Everything looks OK to me ... Debug logs give me nothing.

edit: Should there be anything in ```generated/code/Faonni```?

**Comment by karliuka** [comment]
> Should there be anything in generated/code/Faonni?

no default for this module

**Comment by klou** [comment]
Slight progress -- I manually installed to ```app/code/Faonni/ProductAvailable``` and then I was able to view/access **Catalog->Product Available**.  

However, it didn't have any effect on the front end (i.e. Prices were still shown), and **Catalog->Product Available*** disappeared after clearing cache.

**Comment by klou** [comment]
And now, after a reboot, it works.  I had the same errors (Class not found in AbstractFactory.php:121) with a different extension as well, also installed via composer.

When I installed it (both) manually and restarted, they seem to work.
